In [1]:
import numpy as np
import pandas as pd
import util.Plotly as plots
import util.colors.Colors as colors

In [2]:
pointX = [-73, 73]
pointY = [-107, 75]
pointZ = [-53, 90]
points = [pointX, pointY, pointZ]

In [4]:
sum_list = [abs(x[0]) + abs(x[1]) for x in points]
div = 2
sum_list = [int(x / div) for x in sum_list]
print(sum_list)
vol = np.prod(sum_list)
print(vol)

[73, 91, 71]
471653


In [5]:
# Create points
listX = [x for x in range(pointX[0], pointX[1], div)]
listY = [x for x in range(pointY[0], pointY[1], div)]
listZ = [x for x in range(pointZ[0], pointX[1], div)]

In [6]:
list_coords = [[x, y, z] for x in listX for y in listY for z in listZ if
               not ((y >= 49 and z <= -35) or (y >= 31 and z <= -47) or
                    (y <= -35 and z <= -41) or (y <= -71 and z <= -23) or
                    (y <= -95 and z >= 55) or (y >= 61 and z >= 49) or (
                            y >= 61 and z >= 43) or (z <= -35 and -7 <= x <= 11))]
len(list_coords)

358457

In [29]:
df_brain_coords = pd.DataFrame(list_coords, columns=["MNIX", "MNIY", "MNIZ"])

In [30]:
# save to csv
csv_path = r'data/mni_brain_total.csv'
df_brain_coords.to_csv(csv_path, index=False, header=False)

In [3]:
div = 4
# import points
csv_mni_brain_coords_conv_filename = r'data/mni_brain_total_converted_2.csv'
df_data_mni_conv = pd.read_csv(csv_mni_brain_coords_conv_filename)
df_data_mni_conv = df_data_mni_conv.iloc[::div].reset_index(drop=True)
df_data_mni_conv.head()

MNIX  MNIY  MNIZ                   BA  TALX  TALY  TALZ
0   -73  -107   -21  Outside defined BAs   -71  -105   -13
1   -73  -107   -13  Outside defined BAs   -71  -105    -6
2   -73  -107    -5  Outside defined BAs   -71  -104     0
3   -73  -107     3  Outside defined BAs   -71  -103     7
4   -73  -107    11  Outside defined BAs   -71  -103    14

In [4]:
# filter outside BAs
mask_outside = df_data_mni_conv['BA'].str.contains('Outside defined BAs')
df_data_mni_final = df_data_mni_conv[~mask_outside]
df_test = df_data_mni_conv[mask_outside]

In [5]:
df_data_mni_final.shape

(35109, 7)

In [6]:
len(df_data_mni_final.BA.unique())

82

In [7]:
color_nan = '#ebeded'
color_rest = '#ffe4e1'
color_line = 'rgb(50,50,50)'

color1 = "#800000"
color1_1 = "#CD853f"
color2 = "#556b2f"
color2_1 = "#adff2f"
color3 = "#000080"
color3_1 = "#1e90ff"
color4 = "#b8860B"
color4_1 = "#FFFF00"

In [8]:
cols = dict(x='MNIX',
            y='MNIY',
            z='MNIZ')

In [9]:
#plot points
# Brain data trace
trace_brain_data = plots.create_data(df=df_data_mni_final,cols = cols, grouping_col='BA', colors=color_rest,
                                     labels_col_list=['BA', 'MNIX', 'MNIY', 'MNIZ'],
                                     opacity=0.9, check_nan=True, line_color=color_rest)

In [10]:
#plot points
# # Brain data trace
trace_brain_data_rest = plots.create_data(df=df_test,cols = cols, grouping_col='BA', colors=color_nan,
                                          labels_col_list=['BA', 'MNIX', 'MNIY', 'MNIZ'],
                                          opacity=0.2, check_nan=True, line_color=color_nan)

In [11]:
#Brain points
data_dict_coords = [trace_brain_data]
plots.plot_coordinates_plotly(data=data_dict_coords,
                              data_source_name=csv_mni_brain_coords_conv_filename,
                              title='Center Coordinates - all points')

In [20]:
data =np.array([[18,-7,-28],
        [-17,-3,-14],
        [-28,-24,-14],
        [-21,21,-25]])
print(data)



[[ 18  -7 -28]
 [-17  -3 -14]
 [-28 -24 -14]
 [-21  21 -25]]
