# Test the MNI and Talairach spaces conversions

In [45]:
# import
import numpy as np
import util.Data as data_util
import importlib

In [46]:
importlib.reload(data_util)

<module 'util.Data' from 'D:\\scul\\uaic-ub\\licenta\\code\\util\\Data.py'>

In [47]:
#electrode locations
base_locs = np.array([[56, -15, 50],
                      [-59, -18, 43],
                      [59, -21, 21],
                      [-50, -18, 18],
                      [-5.12, -82.33, 10.8],
                      [2.3, -77.71, 11.37],
                      [15.36, -62.35, 7.64],
                      [45.18, 15.75, 15.54],
                      [2.28, -77.88, 13.15],
                      [-6, -68.35, 12.11],
                      [-56.89, -63.43, 11.72],
                      [49.74, 15.21, 20.97]])

In [48]:
# convert to mni space
mni_locs = data_util.tal2mni(base_locs, no_decimals=2)
mni_locs

array([[ 61.39, -10.05,  51.83],
       [-61.54, -14.56,  45.81],
       [ 64.38, -18.86,  20.19],
       [-52.13, -16.64,  18.  ],
       [ -3.98, -85.  ,  15.15],
       [  3.94, -80.01,  15.28],
       [ 17.8 , -64.01,   9.62],
       [ 49.42,  19.44,  11.06],
       [  3.93, -80.04,  17.26],
       [ -4.96, -70.11,  15.37],
       [-59.37, -65.26,  15.16],
       [ 54.34,  19.37,  17.07]])

In [49]:
# convert to tal space
tal_locs = data_util.mni2tal(base_locs, no_decimals=2)
tal_locs

array([[ 50.95, -19.48,  47.93],
       [-56.61, -21.05,  40.24],
       [ 53.95, -23.03,  21.51],
       [-48.01, -19.29,  17.92],
       [ -6.15, -79.5 ,   7.09],
       [  0.8 , -75.25,   8.02],
       [ 13.09, -60.63,   5.97],
       [ 41.17,  11.98,  19.23],
       [  0.77, -75.54,   9.61],
       [ -6.94, -66.46,   9.3 ],
       [-54.54, -61.47,   8.8 ],
       [ 45.39,  11.05,  24.11]])

In [50]:
result_tal2mni = np.array([[61.39, -10.05, 51.83],
                           [-61.54, -14.56, 45.81],
                           [64.38, -18.86, 20.19],
                           [-52.13, -16.64, 18],
                           [-3.98, -85, 15.15],
                           [3.94, -80.01, 15.28],
                           [17.8, -64.01, 9.62],
                           [49.42, 19.44, 11.06],
                           [3.93, -80.04, 17.26],
                           [-4.96, -70.11, 15.37],
                           [-59.37, -65.26, 15.16],
                           [54.34, 19.37, 17.07]])



In [51]:
assert np.array_equal(result_tal2mni, mni_locs), "The Talairach to MNI transform didn't went well"

In [52]:
result_mni2tal = np.array([[50.95, -19.48, 47.93],
                           [-56.61, -21.05, 40.24],
                           [53.95, -23.03, 21.51],
                           [-48.01, -19.29, 17.92],
                           [-6.15, -79.5, 7.09],
                           [0.8, -75.25, 8.02],
                           [13.09, -60.63, 5.97],
                           [41.17, 11.98, 19.23],
                           [0.77, -75.54, 9.61],
                           [-6.94, -66.46, 9.3],
                           [-54.54, -61.47, 8.8],
                           [45.39, 11.05, 24.11]])

In [53]:
assert np.array_equal(result_mni2tal, tal_locs), "The MNI to Talairach transform didn't went well"

In [56]:
data_util.tal2mni(np.array([[32.00000,-55.00000,38.00000]]))

array([[ 35.805 , -53.5291,  42.3877]])